discuss/lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DiscussWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussWeb do
    pipe_through :browser

    resources "/topics", TopicController

    get "/", TopicController, :index
    # get "/topics/:id", TopicController, :show
    # get "/topics/new", TopicController, :new
    # get "topics/:id/edit", TopicController, :edit
    # post "topics", TopicController, :create
    # put "topics/:id", TopicController, :update
    # delete "topics/:id", TopicController, :delete
  end

  scope "/auth", DiscussWeb do
    pipe_through :browser

    delete "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)
      live_dashboard("/dashboard", metrics: DiscussWeb.Telemetry)
    end
  end
end

discuss/lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

discuss/lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <title>Discuss · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script src="https://kit.fontawesome.com/41479bad2e.js" crossorigin="anonymous"></script>
    <script>
      <%= if @conn.assigns[:user] != nil do %>
        window.userToken = "<%= Phoenix.Token.sign(DiscussWeb.Endpoint, "key", @conn.assigns.user.id) %>"
      <% else %>
        window.userToken = "<%= Phoenix.Token.sign(DiscussWeb.Endpoint, "key", "none") %>"
      <% end %>
    </script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation" class="navbar navbar-expand-lg navbar-light bg-light">
          <%= link to: Routes.topic_path(@conn, :index), class: "navbar-brand" do %>
            <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo" width="180" class="d-inline-block align-top img-fluid" loading="lazy"/>
          <% end %>
          <button class="navbar-toggler ml-3" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" ia-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="https://hexdocs.pm/phoenix/overview.html">Get Started</a>
              </li>
              <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                <li class="nav-item"><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "nav-link" %></li>
              <% end %>
              <li class="nav-item">
                <a class="nav-link" href="/">Discussions</a>
              </li>
              <li class="nav-item">
                <%= if @conn.assigns[:user] do %>
                  <%= link "Logout", to: Routes.auth_path(@conn, :signout), method: :delete, class: "nav-link text-white btn btn-primary ml-3" %>
                <% else %>
                  <%= link "Github Sign In", to: Routes.auth_path(@conn, :request, "github"), class: "nav-link text-white btn btn-primary ml-3" %>
                <% end %>
              </li>
            </ul>
          </div>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>